<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';
require_once __DIR__ . '/../../controllers/Mailer/SendMailer.php';

return ComposerAutoloaderInitdc5d765c1aa9acc4e994e092e5b72245::getLoader();
