<div style="padding-top:20px;text-align:left">Вы подали заявку на изменение пароля от Вашего аккаунта на сайте Vime. Для того чтобы изменить пароль, перейдите по следующей ссылке:
		<br><br>
		<a href="<?=$this->option['user_url_form']?>" target="_blank" ><?=$this->option['user_url_form']?></a>

		<br><br>
		Ссылка будет доступна в течение <?=$this->option['time_life_tempid']?> часов.
		<br><br>
		Если Вы не запрашивали смену пароля от Вашего аккаунта на сайте Vime, проигнорируйте это письмо.
		<br><br>
		С уважением, Ваш Vime.
		<br><br>
		</div>