<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <?php echo $this->tag->getTitle(); ?>
        <?//  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">?>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->url->get('css/style.css?v=1')?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->url->get('css/style.min.css?v=1')?>">
    </head>
    <body>






            <?php echo $this->getContent(); ?>




        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
     <?//   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>?>
        <script src="<?php echo $this->url->get('js/common.min.js?=v1')?>""></script>
        <script src="<?php echo $this->url->get('js/home.min.js?=v1')?>""></script>

        <script src="<?php echo $this->url->get('js/script.js?=v1')?>"></script>
    </body>
</html>
