<div class="footer-clear"></div>

<footer class="footer">
	<div class="container">
		<img src="/img/logo.png" alt="logo" class="footer__logo"> <br>
		<span class="footer__text footer__text_blue">Vime–вільний метр, 2018</span>
		<div class="footer-bottom">
			<span class="footer__text footer__text_mr">&copy; Все права защищены.</span>
			<span class="footer__text">Использование материалов разрешено только при наличии активной ссылки на источник.</span>
			<a href="https://smartorange.com.ua/">
				<img src="/img/smart-orange-logo.png" alt="smartOrange" class="smart-orange-logo">
			</a>
		</div>
	</div>
</footer>