<header class="header header-home">
	<div class="container">
		<a href="/" class="logo__link">
			<img src="/img/logo.png" alt="" class="logo__image">
		</a>
        <?php echo $this->elements->getMenu();?>
	</div>
	<div class="header-content">
		<div class="container clearfix">
			<div class="header__button-wrap">
				<button class="button header__button">Регистрация</button>
				<button class="button header__button">Вход</button>
			</div>
		</div>
	</div>
</header>